version: "3"
services:
  postgres:
    container_name: postgres_container
    image: postgis/postgis:14-3.4-alpine
#    build:
#      context: ../postgres
#      dockerfile: ../postgres/postgres.dockerfile
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../server-service/.env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data/

  server-service:
    container_name: server-service_container
    build:
      context: ../server-service
      dockerfile: ../server-service/server-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
    env_file:
      - ../server-service/.env.prod

  client-service:
    container_name: client-service_container
    build:
      context: ../client-service
      dockerfile: ../client-service/client-service.dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app
      - /app/node_modules
    depends_on:
      - server-service
    env_file:
      - ../client-service/.env

volumes:
  pgdata: {}
