version: "3"

services:
  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8181:8080"
    env_file:
      - ./.env.prod
    command: ["start-dev"]

  postgres:
    container_name: postgres_container
    image: postgis/postgis:14-3.4-alpine
#    build:
#      context: ../postgres
#      dockerfile: ../postgres/postgres.dockerfile
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./.env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data/

  server-service:
    container_name: server-service_container
    build:
      context: ../server-service
      dockerfile: ../server-service/server-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - keycloak
    env_file:
      - ./.env.prod

  client-service:
    container_name: client-service_container
    build:
      context: ../client-service
      dockerfile: ../client-service/client-service.dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app
      - /app/node_modules
    depends_on:
      - server-service
      - keycloak
    env_file:
      - ./.env.prod

volumes:
  pgdata: {}
