version: "3"

services:
  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8181:8080"
    env_file:
      - ./.env.prod
    volumes:
      - keycloakdata:/opt/keycloak/data/
    networks:
      - backend
      - frontend
    command: ["start-dev"]

  postgres:
    container_name: postgres_container
    image: postgis/postgis:14-3.4-alpine
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./.env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend

  aggregation:
    container_name: aggregation_container
    build:
      context: ../aggregation
      dockerfile: ../aggregation/aggregation.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - keycloak
    env_file:
      - ./.env.prod
    networks:
      - backend

  web:
    container_name: web_container
    build:
      context: ../web
      dockerfile: ../web/web.dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app
      - /app/node_modules
    depends_on:
      - aggregation
      - keycloak
    env_file:
      - ./.env.prod
    networks:
      - frontend

volumes:
  pgdata:
  keycloakdata:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge