version: "3"

services:
#  keycloak:
#    container_name: keycloak_container
#    image: quay.io/keycloak/keycloak:24.0.2
#    ports:
#      - "8181:8080"
#    env_file:
#      - ./.env
#    volumes:
#      - keycloakdata:/opt/keycloak/data/
#    command: ["start-dev"]

  postgres:
    container_name: postgres_container
    image: postgis/postgis:14-3.4-alpine
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../aggregation/.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  aggregation:
    container_name: aggregation_container
    build:
      context: ../aggregation
      dockerfile: ../aggregation/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
#      - keycloak
    env_file:
      - ../aggregation/.env

#  web:
#    container_name: web_container
#    build:
#      context: ../web
#      dockerfile: ../web/Dockerfile
#    restart: always
#    volumes:
#      - /app
#      - /app/node_modules
#    depends_on:
#      - aggregation
#      - keycloak
#    env_file:
#      - ../web/.env

#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - /etc/letsencrypt:/etc/letsencrypt
#    restart: always
#    depends_on:
#      - web
#      - aggregation

volumes:
  pgdata:
  keycloakdata:
