# https://habr.com/ru/companies/slurm/articles/704208/
version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    restart: always
    env_file:
      - ../infra/.env
    volumes:
      - ./db-data/rabbitmq:/var/lib/rabbitmq

  postgres:
    image: 'postgres:14.0-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../server-service/.env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  server-service:
    build:
      context: ../server-service
      dockerfile: ../server-service/server-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
    env_file:
      - ../server-service/.env

  client-service:
    build:
      context: ../client-service
      dockerfile: ../client-service/client-service.dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app
      - /app/node_modules
    depends_on:
      - server-service
    env_file:
      - ../client-service/.env