DROP TABLE IF EXISTS profile_complaints;
DROP TABLE IF EXISTS profile_telegram;
DROP TABLE IF EXISTS profile_navigators;
DROP TABLE IF EXISTS profile_images;
DROP TABLE IF EXISTS profile_filters;
DROP TABLE IF EXISTS profile_reviews;
DROP TABLE IF EXISTS profile_likes;
DROP TABLE IF EXISTS profile_blocks;
DROP TABLE IF EXISTS profiles;